name: create a comment on a issues
'on':
  issue:
    types:
      - opened
jobs:
  comment-with-action: null
  runs-on: ubuntu-latest
  steps:
    - name: dump github context
      run: 'echo "${{toJSON(gitbun.event)}}" | jq'
      shell: bash
